### ISSUE TITLE
next steps for metadata editor

### ISSUE THREAD

**Issue by sethvincent** [openaq/openaq-metadata-editor#42]
@jflasher @olafveerman here are the rough next steps for getting this deployed on staging so it can be tested out. Let me know if I'm missing anything or if you have questions

### tasks for @jflasher 
- [x] review openaq-api pr https://github.com/openaq/openaq-api/pull/403
- [x] review openaq-data-format pr https://github.com/openaq/openaq-data-format/pull/18
- [x] review openaq.org pr https://github.com/openaq/openaq.org/pull/290
- [ ] review current state of openaq-metadata-editor (probably best to do this after we set up staging)
- [x] set up dns for metadata project: metadata.openaq.org, metadata.openaq-staging.org
- [x] set up buckets for the metadata project with same dns names
- [x] set up cloudfront for metadata project similar to how openaq.org is set up

### tasks for @sethvincent & team after the above is complete
- [x] make any fixes needed to the various prs
- [x] merge schema pr for openaq-data-format
- [x] update repos that have a dependency on oenaq-data-format
- [x] finish setting up deployment process of openaq-metadata-editor
- [x] merge open prs on openaq-api, openaq.org, openaq-metadata-editor
- [x] do QA on the staging environment

**Comment by jflasher** [comment]
@sethvincent thanks for all of this (and everyone else who has touched it so far)! There is one (small) wrinkle I listed in the openaq-api PR but everything looks good to merge. I think you are able to merge everything in, if that's not the case, let me know. If you want me to merge anything in (as I can likely monitor for initial failures more easily), just let me know what order you'd like it all done in. 

For the deployment of the metadata editor, you'll probably need my help in allowing write access to the S3 buckets, just let me know when I can help there. As an FYI, we still haven't received access to GitHub Actions beta.

**Comment by sethvincent** [comment]
@jflasher thanks! I'll get most of the merging completed today.

Could you create and send me the encrypted env vars for the s3 access keys for the relevant buckets?

**Comment by jflasher** [comment]
Thanks @sethvincent! Following same pattern as https://github.com/openaq/openaq.org/blob/develop/.travis.yml, key_id is the same and encrypted secret is `JmalFAU1SCF2NruC1FjpsfvBPMyyZAc0FrFefki8mC6r8QamQyv/xesq0KPQlraA1Lll0dE1b7qMdoSZNZIR8itzOlDQZXC4Hnu4HEd+vOhAkkVlCPSxF3yGvL/i2OGL+ocJmY5tlGcPzWD8TSBpLFlML5dUhUwAWIhxDXnHQuAFaC/yIkmO2lq3ldSwAy/4CVX+24wh2kg8pNms0T9FVTGSirERJwMsUFLKzXtcUd0QLWZ1j2Fao1CClSiiRX2841F0UNIkQOm5XFbIii4iCr+xtq+U1LmqoMnGi78WwR0JuZ+WgbPFfxXuHHVtQrVngOWGrSm0SJwx+IplqwVq1u/IQM+vAK36UIv0at5vZ77eGP4wOnpBA2J/Vdie/41/4+E4aIxcUBFZmtdfwolSdT9LXJrJP8KgmV3suwcbX5h/8/6dsI+7pGTi+CX9fQ4Ecs0rUtBmynNV4SP6jgJoylDRoZHAf/HZCs//JsA2nbO8E5JUf5tLAHTU0aDEI7EaMdtDO46EYnQhbeHp5MdnFrz6jZm42FqkYsIaA423X4cYsDuRph1IV6gqJiSzeGwfyDxDCFYke2+uEm3CDu10jCdTaNMcchdpg7/1VUjdq3V+A+uz8Eq/OeK1JRfPkFD7RzcJx18nNNMjHQQkiknjJc8/jNKzc9GZSjADXWFRpoo=`

let me know if you run into any issues.

**Comment by sethvincent** [comment]
@jflasher we've got deployment to staging all set up. Currently seeing an access denied error at https://metadata.openaq-staging.org

**Comment by jflasher** [comment]
@sethvincent sorry, I forgot to set default object in CloudFront, that's updating now. In the meantime, I think https://metadata.openaq-staging.org/index.html may work.

**Comment by sethvincent** [comment]
Things are now set up and we can now do some testing on staging. Closing this issue, and we can make new issues for specific things we find during testing.
