### ISSUE TITLE
remove editing of coordinates, use location coordinates populated by openaq-fetch

### ISSUE THREAD

**Issue by sethvincent** [openaq/openaq-metadata-editor#59]
~Right now it's not clear that the map on the edit form is the approach used to add/edit coordinates.~

Todo:
- [ ] using the coordinates reported by openaq-fetch ( #68 )
- [ ] remove editing capabilities of the coordinates ( #66 ) 
- [ ] provide help text with the site notes field about reporting errors ( #67 )
- [ ] making related changes in the schema in openaq-data-format if needed ([PR](openaq/openaq-data-format#19))

**Comment by necoline** [comment]
I think the main issue is that the form header containing the map looks like it is set summary information. If a user wants to update for example, the location type, they must do so in the form. 

I propose that we add a new section to the form with the coordinates in a text input box and the editable map with instructions on how to update the map.

Should it be possible to add a second point to the map?

**Comment by sethvincent** [comment]
@necoline I totally agree. A new section that more clearly looks like part of the form input sounds like the way to go.

There should only ever be one point, though it should be easy to change the location of the point.

**Comment by olafveerman** [comment]
Coordinates are reported by the data provider, and don't think they should be editable by users.

cc @RocketD0g @jflasher

**Comment by RocketD0g** [comment]
While I think that the data provider coordinates should generally be the ones we use as default, these do have errors sometimes (e.g. null islands, or sometimes sources will move stations physically, but not update their coordinates online, which technically create a new station in our system), and it'd be cool if users could call out what they think are errors. 

Maybe we can just call out that coordinate errors (or errors in general) can be reported in the "site notes" area? And/or perhaps some way for a user to flag when they are reporting an error, like a box they tick? This way, we can see when a potential error is being reported (so it doesn't just get buried in the text of the notes)? In this way, the information can theoretically be brought back to the data provider to potentially adjust what coordinates/info they are putting out.

**Comment by sethvincent** [comment]
Got it. That's good to know. Let's change this issue to make it about:

- using the coordinates reported by openaq-fetch
- remove editing capabilities of the coordinates
- provide help text with the site notes field about reporting errors
- making related changes in the schema in openaq-data-format if needed

I'll update the title & issue text.

**Comment by necoline** [comment]
Would it make sense to add a checkbox to mark if there is an error with the coordinates? This way, further down the line, it would be easy for the data provider to search for coordinate errors and correct them.

https://github.com/openaq/openaq-data-format/pull/19
